language: csharp
solution: SocksRelayServer/SocksRelayServer.sln
mono: none
dotnet: 2.1
services:
  - docker
before_install:
  - docker pull wernight/dante
  - docker run -d -p 1080:1080 wernight/dante
script:
  - dotnet test SocksRelayServer/Tests/Tests.csproj
