language: csharp
mono: none
dotnet: 2.1
services:
  - docker
before_install:
  - docker pull wernight/dante
  - docker run -d -p 1080:1080 wernight/dante
script:
  - dotnet test --verbosity detailed SocksRelayServer/Tests/Tests.csproj
